# Change these first
owner: Amia33 # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

user-agent: Amia33
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
sites:
  - name: Bitbucket
    url: $LATENCY_BITBUCKET
    icon: https://bitbucket.org/favicon.ico?v=2
  - name: Github
    url: $LATENCY_GITHUB
    icon: https://github.githubassets.com/favicons/favicon.svg
  - name: Gitlab
    url: $LATENCY_GITLAB
    icon: https://gitlab.com/assets/favicon-yellow-018213ceb87b472388095d0264be5b4319ef47471dacea03c83ecc233ced2fd5.png
  - name: Google Firebase
    url: $LATENCY_FIREBASE
    icon: https://www.gstatic.com/mobilesdk/160503_mobilesdk/logo/favicon.ico
  - name: Sourceforge
    url: $LATENCY_SOURCEFORGE
    icon: https://a.fsdn.com/con/img/sandiego/logo-180x180.png
  - name: Surge
    url: $LATENCY_SURGE
    icon: https://surge.sh/images/logos/svg/surge-logo.svg

assignees: # Users to assign downtime issues (optional)
  - Amia33

status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: test.amia.work
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Amia33/Amia33/master/files/logo.png
  favicon: https://raw.githubusercontent.com/Amia33/Amia33/master/files/favicon.ico
  customHeadHtml: ""
  customBodyHtml: "<!-- Cloudflare Web Analytics -->  <script defer src='https://static.cloudflareinsights.com/beacon.min.js?token=081a7d0124c8485397ce49033caf0067'></script><!-- End Cloudflare Web Analytics -->"
  robotsText: "User-agent: * \n Disallow: /"
  name: Upptime for Amia
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: /
    - title: BlogStatus
      href: https://test.amia.work/history/blog

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
